language: php

php:
  - 7.0
  - 7.1

before_install:
  - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then pecl install mongodb; fi
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist && make sniff

after_script:
  - php vendor/bin/coveralls -v
