language: php

php:
  - 7.0
  - hhvm

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION = 'hhvm' ]]; then echo "extension = mongodb.so" >> /etc/hhvm/php.ini; fi

before_script:
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist && make sniff

after_script:
  - php vendor/bin/coveralls -v
