site_name: "Mongolid ODM"
site_url: http://leroy-merlin-br.github.io/mongolid
repo_url: https://github.com/leroy-merlin-br/mongolid

theme: readthedocs

nav:
    - 'Home': 'index.md'
    - 'Basics': 'basics.md'
    - 'Relationships': 'relationships.md'
    - 'API Documentation': 'api-docs.md'
    - 'Troubleshooting': 'troubleshooting.md'
    - 'Additional information': 'info.md'

markdown_extensions:
    - def_list
    - fenced_code
    - smarty
    - toc:
        permalink: true
